name: sqfentity_gen
homepage: https://github.com/hhtokpinar/sqfEntity
description: SqfnEntity Model Generator. SQLite ORM for Flutter lets you build and execute SQL commands easily and quickly with the help of fluent methods similar to .Net Entity Framework.

version: 2.5.0
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  build: ^4.0.3
  source_gen: ^4.1.1
  meta: ^1.17.0
  analyzer: ^8.1.1
  intl: ^0.20.2
