name: sqfentity_gen
homepage: https://github.com/hhtokpinar/sqfEntity
description: SqfnEntity Model Generator. SQLite ORM for Flutter lets you build and execute SQL commands easily and quickly with the help of fluent methods similar to .Net Entity Framework.

version: 2.5.0
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  build: ^2.4.1
  source_gen: ^1.5.0
  meta: ^1.12.0
  analyzer: ^6.2.0
  intl: ^0.19.0

dev_dependencies:
  build_runner: ^2.4.6
  build_test: ^2.2.0
  test: ^1.24.9
  mockito: ^5.4.2
